# Default values for mongodb-bi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
# In order to run this helm chart you have to build and push docker image in your registry
# See Dockerfile
image:
  # repository: docker-image
  tag: 0.0.27
  pullPolicy: Always
  repository: jx3mqubebuild.azurecr.io/spring-financial-group/mongodb-bi-chart
imagePullSecrets: {}
#   - name: pull-secrets

nameOverride: ""
fullnameOverride: ""
service:
  type: LoadBalancer
  port: 3307
ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
readinessProbe:
  tcpSocket:
    port: 3307
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  tcpSocket:
    port: 3307
  initialDelaySeconds: 15
  periodSeconds: 20
auth:
  host: mongodb
  port: 27017
  user: root
  password:
    secretName: mongodb-password
    secretKey: password
